#!/usr/bin/env bash
# Creates both database roles for one environment, and hands the schema to the migrator.
#
# Why two roles: the app should be able to move rows and nothing else. If it connects as the
# owner, a bug — or a model-generated query, or an injection — can DROP a table, and the
# blast radius of every other mistake grows to match. So migrations get their own
# credentials and the running app keeps none of that power.
#
# The cost is one real failure mode to know about: a migration run with the app's own
# credentials fails with "must be owner of table …". That message means the wrong
# FLYWAY_USER, not a broken migration.
#
# Run as root:  sudo bash deploy/setup-db.sh <database> <app_role> <env_file>
# Safe to run twice.
set -euo pipefail

if [[ $# -ne 3 ]]; then
  echo "usage: $0 <database> <app_role> <env_file>" >&2
  exit 64
fi

db="$1"; app_role="$2"; env_file="$3"
cd /tmp   # psql runs as postgres, which cannot read root's home

migrator_role=$(grep '^FLYWAY_USER=' "$env_file" | cut -d= -f2-)
migrator_pw=$(grep '^FLYWAY_PASSWORD=' "$env_file" | cut -d= -f2-)

if [[ -z "$migrator_role" || -z "$migrator_pw" ]]; then
  echo "!! $env_file has no FLYWAY_USER / FLYWAY_PASSWORD" >&2
  exit 1
fi

echo "── $db: $migrator_role owns the schema, $app_role keeps data access ──"

# Checked from the shell because CREATE ROLE has no IF NOT EXISTS, and psql does not
# interpolate its variables inside a DO block's body.
exists=$(sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname = '$migrator_role'")
if [[ "$exists" == "1" ]]; then
  sudo -u postgres psql -q -v ON_ERROR_STOP=1 -v role="$migrator_role" -v pw="$migrator_pw" <<'SQL'
ALTER ROLE :"role" LOGIN PASSWORD :'pw';
SQL
  echo "   role already existed — password refreshed"
else
  sudo -u postgres psql -q -v ON_ERROR_STOP=1 -v role="$migrator_role" -v pw="$migrator_pw" <<'SQL'
CREATE ROLE :"role" LOGIN PASSWORD :'pw';
SQL
  echo "   role created"
fi

sudo -u postgres psql -q -v ON_ERROR_STOP=1 -d "$db" \
  -v migrator="$migrator_role" -v app="$app_role" <<'SQL'
-- It has to own what it alters, and be able to create what comes next.
ALTER SCHEMA public OWNER TO :"migrator";

-- Ownership is handed over one object at a time, generated by the query and run by \gexec —
-- a DO block would need the role name inside its body, where psql variables do not expand.
SELECT format('ALTER TABLE public.%I OWNER TO %I', tablename, :'migrator')
FROM pg_tables WHERE schemaname = 'public';
\gexec

SELECT format('ALTER SEQUENCE public.%I OWNER TO %I', sequencename, :'migrator')
FROM pg_sequences WHERE schemaname = 'public';
\gexec

-- The app keeps exactly what it had: rows, not structure.
GRANT USAGE ON SCHEMA public TO :"app";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO :"app";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO :"app";

-- And keeps it on tables the migrator creates later, without anyone remembering to grant.
-- Without this, the next migration creates a table the app cannot read.
ALTER DEFAULT PRIVILEGES FOR ROLE :"migrator" IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"app";
ALTER DEFAULT PRIVILEGES FOR ROLE :"migrator" IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO :"app";
SQL

echo "   schema and grants done"
